name: Publish API

on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Publish via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22        
        script: |
            export AUTH_SECRET_KEY='${{ secrets.AUTH_SECRET_KEY }}' 
            export PORT='${{ secrets.PORT }}'
            export SPREADSHEET_ID='${{ secrets.SPREADSHEET_ID }}'

            cd apps
            cd CongGuaraniNorteTerritory
            
            echo 'Update data...'
            git pull
            git status

            sleep 5
            echo ''
            echo 'Publish on Docker and restart'
            IMAGE_NAME=congguaraninorte-front
            VPS_NETWORK=vps-network

            echo ''
            echo "removendo node modules"
            rm node_modules -r

            echo ''
            echo "Limpando versão anterior..."
            docker rm -f $IMAGE_NAME || true

            echo ''
            echo "Contruindo imagem"
            docker build -t $IMAGE_NAME .

            echo ''
            echo "Contruindo Container"
            docker run -d \
                --network $VPS_NETWORK \
                --name $IMAGE_NAME \
                -e AUTH_SECRET_KEY=$AUTH_SECRET_KEY \
                -e PORT=$PORT \
                -e SPREADSHEET_ID=$SPREADSHEET_ID \
                $IMAGE_NAME

            echo ''
            echo 'Sucessfully Published!'
    - name: Validando Container via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
            echo "Validando se container está OK"
            IMAGE_NAME=congguaraninorte-front
            sleep 10
            OUTPUT=$(docker logs $IMAGE_NAME 2>&1)

            echo "===== OUTPUT ====="
            echo "$OUTPUT"
            echo "=================="

            if [[ "$OUTPUT" == *"ERROR"* ]]; then
                echo "❌ Encontrado ERROR no output"
                exit 1
            else
                echo "✅ Nenhum erro encontrado"
            fi
