name: Deploy on PRD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Publish via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22        
        script: |
            export AUTH_SECRET_KEY='${{ secrets.AUTH_SECRET_KEY }}' 
            export PORT='${{ secrets.PORT }}'
            export SPREADSHEET_ID='${{ secrets.SPREADSHEET_ID }}'
            export REPO_FOLDER='${{ github.event.repository.name }}'
            IMAGE_NAME=congguaraninorte-front
            VPS_NETWORK=vps-network

            cd apps

            if [ -d "$REPO_FOLDER" ]; then
              echo "Repo já existe, atualizando..."
              cd $REPO_FOLDER
              git fetch --all
              git reset --hard origin/main
            else
              echo "Clonando repositório..."
              git clone git@github.com:${{ github.repository }}.git
              cd $REPO_FOLDER
            fi
            pwd
            
            echo 'Update data...'
            git pull
            git status

            echo 'Getting Google credentials'
            mkdir google_auth
            cp ~/apps/credentials.json google_auth/credentials.json

            echo 'Checking folder'
            pwd

            sleep 5
            echo ''
            echo 'Publish on Docker and restart'

            echo ''
            echo "Contruindo Container"
            docker compose up -d --build

            echo ''
            echo 'Sucessfully Published!'
    - name: Validando Container via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
            echo "Validando se container está OK"
            IMAGE_NAME=congguaraninorte-front

            sleep 10

            for i in $(seq 1 5); do
              STATUS=$(docker inspect --format='{{.State.Health.Status}}' $IMAGE_NAME)

              if [ "$STATUS" == "healthy" ]; then
                echo "✅ Container saudável"
                exit 0
              fi

              echo "⏳ Ainda não saudável ($STATUS)..."
              sleep 5
            done

            echo "❌ Container não ficou saudável"
            docker logs $IMAGE_NAME
            exit 1
